// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC167VbXXP3LQON3xJ1-vdmIJu2j4DgMD8',
    appId: '1:1026300338820:web:de4de40f5c9b8cab8dd8d1',
    messagingSenderId: '1026300338820',
    projectId: 'caretutors-bcc29',
    authDomain: 'caretutors-bcc29.firebaseapp.com',
    storageBucket: 'caretutors-bcc29.appspot.com',
    measurementId: 'G-2ED5NQ77PN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW2UjMJhfm8485uJwRXNs_iiGDSemGiyA',
    appId: '1:1026300338820:android:793362a699a5a80e8dd8d1',
    messagingSenderId: '1026300338820',
    projectId: 'caretutors-bcc29',
    storageBucket: 'caretutors-bcc29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO1llpMxSe4iXjjsLuewaFWXAz6JN9EKw',
    appId: '1:1026300338820:ios:9632dd8d1b1e98458dd8d1',
    messagingSenderId: '1026300338820',
    projectId: 'caretutors-bcc29',
    storageBucket: 'caretutors-bcc29.appspot.com',
    iosBundleId: 'com.example.caretutors',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO1llpMxSe4iXjjsLuewaFWXAz6JN9EKw',
    appId: '1:1026300338820:ios:9632dd8d1b1e98458dd8d1',
    messagingSenderId: '1026300338820',
    projectId: 'caretutors-bcc29',
    storageBucket: 'caretutors-bcc29.appspot.com',
    iosBundleId: 'com.example.caretutors',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC167VbXXP3LQON3xJ1-vdmIJu2j4DgMD8',
    appId: '1:1026300338820:web:7c02cd0435822a088dd8d1',
    messagingSenderId: '1026300338820',
    projectId: 'caretutors-bcc29',
    authDomain: 'caretutors-bcc29.firebaseapp.com',
    storageBucket: 'caretutors-bcc29.appspot.com',
    measurementId: 'G-N3FQ62JV7N',
  );

}